Allow for setting ipset maxlen otherwise blocklists are too long for the default

diff --git a/templates/firewall-ipset.j2 b/templates/firewall-ipset.j2
--- a/templates/firewall-ipset.j2
+++ b/templates/firewall-ipset.j2
@@ -7,7 +7,7 @@ IPCMD=$(command -v ipset)
 # 24 days 2073600
 # current max is 24 days - see https://marc.info/?l=netfilter-devel&m=141337202317570&w=2
 TIMEOUT={{ firewall_ipset_timeout }}
-
+MAXELEM={{ firewall_ipset_bl_maxelem | default('100000') }}
 
 # simple ipset create
 function createIPSET {
@@ -52,7 +52,7 @@ function createIPSET-Timeout {
 
 if [ "$ipset_exists" == "false" ];then
  echo "Create $IPSET"
- $IPCMD create "$IPSET" "$IPTYP" hashsize 4096 timeout "$IPTME" -exist || { echo "$0: Unable to create ipset: $IPSET" >&2; exit 2; }
+ $IPCMD create "$IPSET" "$IPTYP" hashsize 4096 maxelem "$MAXELEM" timeout "$IPTME" -exist || { echo "$0: Unable to create ipset: $IPSET" >&2; exit 2; }
 else
   echo "$IPSET exists and is timeout compatable"
 fi
